//
// Created by dom on 24/10/21.
//

#ifndef ALGORITHMS_NORMAL_DISTRIBUTIONS_TRANSFORM_H
#define ALGORITHMS_NORMAL_DISTRIBUTIONS_TRANSFORM_H

#endif //ALGORITHMS_NORMAL_DISTRIBUTIONS_TRANSFORM_H

class NDT
{
public:
    static int ndt();
};
